export const demoJoueurs = [
    { id: '1', nom: 'Isma', username: 'Isma', password: 'Coach2025', role: 'coach' },
    { id: '2', nom: 'Hicham', username: 'Hicham', password: 'Cappelle1234', role: 'joueur' },
    { id: '3', nom: 'Allan D', username: 'AllanD', password: 'Cappelle5678', role: 'joueur' },
    { id: '4', nom: 'Allan T', username: 'AllanT', password: 'Cappelle9012', role: 'joueur' },
    { id: '5', nom: 'Babak', username: 'Babak', password: 'Cappelle3456', role: 'joueur' },
    { id: '6', nom: 'Ben', username: 'Ben', password: 'Cappelle7890', role: 'joueur' },
    { id: '7', nom: 'Bob', username: 'Bob', password: 'Cappelle2345', role: 'joueur' },
    { id: '8', nom: 'Chico', username: 'Chico', password: 'Cappelle6789', role: 'joueur' },
    { id: '9', nom: 'Christopher', username: 'Christopher', password: 'Cappelle0123', role: 'joueur' },
    { id: '10', nom: 'Iheb', username: 'Iheb', password: 'Cappelle4567', role: 'joueur' },
    { id: '11', nom: 'Jason', username: 'Jason', password: 'Cappelle8901', role: 'joueur' },
    { id: '12', nom: 'Jordan', username: 'Jordan', password: 'Cappelle2346', role: 'joueur' },
    { id: '13', nom: 'Kevin', username: 'Kevin', password: 'Cappelle6780', role: 'joueur' },
    { id: '14', nom: 'Lionel', username: 'Lionel', password: 'Cappelle0124', role: 'joueur' },
    { id: '15', nom: 'Ludovic', username: 'Ludovic', password: 'Cappelle4568', role: 'joueur' },
    { id: '16', nom: 'Mathis', username: 'Mathis', password: 'Cappelle8902', role: 'joueur' },
    { id: '17', nom: 'Mohamed', username: 'Mohamed', password: 'Cappelle2347', role: 'joueur' },
    { id: '18', nom: 'Nolan', username: 'Nolan', password: 'Cappelle6781', role: 'joueur' },
    { id: '19', nom: 'Pierre', username: 'Pierre', password: 'Cappelle0125', role: 'joueur' },
    { id: '20', nom: 'Ringo', username: 'Ringo', password: 'Cappelle4569', role: 'joueur' },
    { id: '21', nom: 'Ryan', username: 'Ryan', password: 'Cappelle8903', role: 'joueur' },
    { id: '22', nom: 'Sanchez', username: 'Sanchez', password: 'Cappelle2348', role: 'joueur' },
    { id: '23', nom: 'Thomas', username: 'Thomas', password: 'Cappelle6782', role: 'joueur' },
    { id: '24', nom: 'Tonio', username: 'Tonio', password: 'Cappelle0126', role: 'joueur' },
    { id: '25', nom: 'Zak', username: 'Zak', password: 'Cappelle4570', role: 'joueur' },
    { id: '26', nom: 'AllanG', username: 'AllanG', password: 'Cappelle1177', role: 'joueur' },
    { id: '27', nom: 'Adam', username: 'Adam', password: 'Cappelle0404', role: 'coach_adjoint' }
  ];
  
  export const demoMatchs = [
    { id: '1', date: '07/09/2025', adversaire: 'ARMBOUTS CAPPEL US', domicile: 'false', statut: 'joue', scoreEquipe: 5, scoreAdversaire: 1 },
    { id: '2', date: '21/09/2025', adversaire: 'MONTS DE FLANDRE US 2', domicile: 'true', statut: 'joue', scoreEquipe: 6, scoreAdversaire: 2 },
    { id: '3', date: '05/10/2025', adversaire: 'DUNKERQUE USL 3', domicile: 'false', statut: 'avenir' },
    { id: '4', date: '19/10/2025', adversaire: 'WALLON CAPPEL US', domicile: 'true', statut: 'avenir' },
    { id: '5', date: '02/11/2025', adversaire: 'HAZEBROUCK AS CHTS', domicile: 'false', statut: 'avenir' },
    { id: '6', date: '09/11/2025', adversaire: 'LEFFRINCKOUCKE US 2', domicile: 'true', statut: 'avenir' },
    { id: '7', date: '23/11/2025', adversaire: 'BOURBOURG SC 2', domicile: 'false', statut: 'avenir' },
    { id: '8', date: '07/12/2025', adversaire: 'PONT DE NIEPPE AS', domicile: 'false', statut: 'avenir' },
    { id: '9', date: '14/12/2025', adversaire: 'STEENE FC', domicile: 'true', statut: 'avenir' },
    { id: '10', date: '08/02/2026', adversaire: 'STEENE FC', domicile: 'false', statut: 'avenir' },
    { id: '11', date: '15/02/2026', adversaire: 'ARMBOUTS CAPPEL US', domicile: 'true', statut: 'avenir' },
    { id: '12', date: '22/02/2026', adversaire: 'MONTS DE FLANDRE US 2', domicile: 'false', statut: 'avenir' },
    { id: '13', date: '08/03/2026', adversaire: 'DUNKERQUE USL 3', domicile: 'true', statut: 'avenir' },
    { id: '14', date: '15/03/2026', adversaire: 'WALLON CAPPEL US', domicile: 'false', statut: 'avenir' },
    { id: '15', date: '12/04/2026', adversaire: 'LEFFRINCKOUCKE US 2', domicile: 'false', statut: 'avenir' },
    { id: '16', date: '26/04/2026', adversaire: 'PONT DE NIEPPE AS', domicile: 'true', statut: 'avenir' },
    { id: '17', date: '10/05/2026', adversaire: 'HAZEBROUCK AS CHTS', domicile: 'true', statut: 'avenir' },
    { id: '18', date: '17/05/2026', adversaire: 'BOURBOURG SC 2', domicile: 'true', statut: 'avenir' }
  ];